.PHONY: up down test lint fmt migrate audit egress

up:      ; docker compose up --build
down:    ; docker compose down
migrate: ; cd backend && alembic upgrade head
test:    ; cd backend && pytest -q
lint:    ; cd backend && ruff check . && mypy app worker
fmt:     ; cd backend && ruff format . && ruff check --fix .
audit:   ; python3 scripts/build_audit_bundle.py
egress:  ; cd backend && . .venv/bin/activate && python ../evaluation/harness/egress_matrix.py > /tmp/eg.txt; \
	cd .. && { echo '# Egress matrix'; echo; echo 'Generated by `make egress`, which exercises the real `EgressGuard`.'; \
	echo 'Regenerate after any change to providers or policy; do not hand-edit.'; echo; \
	echo "Last generated against commit \`$$(git rev-parse --short HEAD)\`."; echo; \
	echo '```'; cat /tmp/eg.txt; echo '```'; } > EGRESS.md && echo "wrote EGRESS.md"
