#!/usr/bin/env python3
"""Regenerate docs/audit/BUNDLE.md — everything an external reviewer needs, current.

Run: make audit

The bundle exists so review does not depend on someone remembering to copy the right
files. It is generated from the working tree and stamped with the commit, so a stale
bundle is visible rather than silent.
"""

from __future__ import annotations

import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

SOURCES = [
    ("Egress policy — the security property", "backend/app/domain/egress.py"),
    ("Egress guard — the single authority", "backend/app/services/egress_guard.py"),
    ("Providers — every content-receiving sink", "backend/app/adapters/providers.py"),
    ("Provider construction", "backend/app/adapters/factory.py"),
    ("Configuration", "backend/app/config.py"),
    ("Tests — egress property matrix", "backend/tests/unit/test_egress_policy.py"),
    ("Tests — bypass attempts (Property 3)", "backend/tests/unit/test_egress_bypass.py"),
    ("Tests — adapter inventory (Property 7)", "backend/tests/unit/test_adapter_inventory.py"),
    ("Tests — network boundary", "backend/tests/unit/test_network_boundary.py"),
    ("Tests — full-text semantics", "backend/tests/integration/test_fulltext_semantics.py"),
]


def run(cmd: list[str], cwd: Path = ROOT) -> str:
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    return (result.stdout + result.stderr).strip()


def main() -> int:
    commit = run(["git", "rev-parse", "--short", "HEAD"])
    subject = run(["git", "log", "-1", "--pretty=%s"])
    dirty = run(["git", "status", "--porcelain"])

    parts: list[str] = []
    parts.append("# Audit bundle\n")
    parts.append(
        "Generated by `make audit`. Do not hand-edit — regenerate instead.\n\n"
        f"- Commit: `{commit}` — {subject}\n"
        f"- Generated: {datetime.now(UTC):%Y-%m-%d %H:%M} UTC\n"
        f"- Working tree: {'**has uncommitted changes**' if dirty else 'clean'}\n"
    )
    parts.append(
        "\n## How to review this\n\n"
        "The design rationale is in `docs/ARCHITECTURE.md`. The security property and its\n"
        "evidence are in `EGRESS.md`, generated by running the real guard. Below is the\n"
        "source those two documents describe, so claims can be checked against code.\n\n"
        "The property under test:\n\n"
        "> Document content classified `confidential` or above never reaches a cloud\n"
        "> provider, through any capability, under any configuration.\n"
    )

    egress = ROOT / "EGRESS.md"
    if egress.exists():
        parts.append("\n---\n\n## Current egress matrix\n\n")
        parts.append(egress.read_text().split("```", 1)[-1].rsplit("```", 1)[0].strip())

    parts.append("\n\n---\n\n## Source under review\n")
    for title, rel in SOURCES:
        path = ROOT / rel
        if not path.exists():
            parts.append(f"\n### {title}\n\n**MISSING: `{rel}`**\n")
            continue
        parts.append(f"\n### {title}\n\n`{rel}`\n\n```python\n{path.read_text().rstrip()}\n```\n")

    out = ROOT / "docs" / "audit" / "BUNDLE.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(parts) + "\n")
    print(f"wrote {out.relative_to(ROOT)} ({out.stat().st_size // 1024} KB) at {commit}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
